spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-AllowCredentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"